version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        cert_path: ${CERT_PATH}
        cert_key_path: ${CERT_KEY_PATH}
    container_name: prestashop_app
    #    environment:
    #  - PS_DEV_MODE=true
    ports:
      - 80:80
      - 443:443
    links:
      # - mysql
      - mailhog
    volumes:
      - prestashop_app:/var/www/html
      - ./mercadopago:/var/www/html/modules/mercadopago
      #- /etc/letsencrypt/live/ltucillo.ppolimpo.io/fullchain.pem:/etc/letsencrypt/live/ltucillo.ppolimpo.io/fullchain.pem
      #- /etc/letsencrypt/live/ltucillo.ppolimpo.io/privkey.pem:/etc/letsencrypt/live/ltucillo.ppolimpo.io/privkey.pem
      - ${CERT_PATH}:${CERT_PATH}
      - ${CERT_KEY_PATH}:${CERT_KEY_PATH}
    networks:
      - prestashop_network

  mysql:
    image: mysql:5.7
    container_name: prestashop_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
    volumes:
      - prestashop_db:/var/lib/mysql
    networks:
      - prestashop_network

  mailhog:
    image: mailhog/mailhog
    container_name: prestashop_mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - prestashop_network

networks:
  prestashop_network:
    driver: bridge

volumes:
  prestashop_app:
  prestashop_db:
