version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-${PRESTASHOP_VERSION}
      args:
        cert_path: ${CERT_PATH}
        cert_key_path: ${CERT_KEY_PATH}
    container_name: prestashop_app-${PRESTASHOP_VERSION}
    environment:
      - PS_DEV_MODE=true
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
      - mailhog
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./mercadopago:/var/www/html/modules/mercadopago
      - ${CERT_PATH}:/certs/cert.pem
      - ${CERT_KEY_PATH}:/certs/cert.key
    networks:
      - prestashop_network

  mysql:
    image: mysql:5.7
    container_name: prestashop_mysql-${PRESTASHOP_VERSION}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
    networks:
      - prestashop_network

  mailhog:
    image: mailhog/mailhog
    container_name: prestashop_mailhog-${PRESTASHOP_VERSION}
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - prestashop_network

networks:
  prestashop_network:
    driver: bridge
